# This YAML file contains driver-registrar & csi driver nodeplugin API objects,
# which are necessary to run csi nodeplugin for cinder.
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: iscsid-config-json
  namespace: kube-system
data:
  iscsi.json: |
    {
      "command": "iscsid -d 8 -f",
      "config_files": []
    }
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cinder-metal-csi-nodeplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cinder-metal-csi-nodeplugin
  template:
    metadata:
      labels:
        app: cinder-metal-csi-nodeplugin
    spec:
      tolerations:
        - operator: Exists
      serviceAccount: cinder-metal-csi-node-sa
      hostNetwork: true
      hostIPC: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.5.0
          args:
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: iscsid
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: kolla/centos-binary-iscsid:yoga
          imagePullPolicy: "IfNotPresent"
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
          volumeMounts:
            - mountPath: /sys
              name: host-sys
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /run
              name: run-dir
            - name: pods-probe-dir
              mountPath: /dev
            - name: iscsid-config-json
              subPath: iscsi.json
              mountPath: /var/lib/kolla/config_files/config.json
        - name: cinder-metal-csi
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: registry.aliyuncs.com/kungze/cinder-metal-csi:main
          imagePullPolicy: "IfNotPresent"
          args:
            - /bin/cinder-metal-csi
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloud-conf=$(CLOUD_CONFIG)"
            - "--node-id=$(NODE_ID)"
            - "--v=3"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: CLOUD_CONFIG
              value: /etc/cloud/cloud.conf
          volumeMounts:
            - mountPath: /sys
              name: host-sys
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /run
              name: run-dir
            - name: pods-probe-dir
              mountPath: /dev
            - name: socket-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: csi-config
              mountPath: /etc/cloud
              readOnly: true
            - name: ceph-keyring-tmp-dir
              mountPath: /tmp/csi/keys
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/cinder.csi.openstack.org
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - name: csi-config
          secret:
            secretName: cinder-metal-csi-config
        - hostPath:
            path: /sys
            type: ""
          name: host-sys
        - hostPath:
            path: /lib/modules
            type: ""
          name: lib-modules
        - hostPath:
            path: /run
            type: DirectoryOrCreate
          name: run-dir
        - configMap:
            defaultMode: 292
            name: iscsid-config-json
          name: iscsid-config-json
        - name: ceph-keyring-tmp-dir
          emptyDir: {}

